services:
  backend:
    build: ./Backend_HMS/Hospital_MS
    image: hms-backend
    container_name: hms-backend
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://hms-db.c76cgaiiy6sz.eu-north-1.rds.amazonaws.com:3306/hmsdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=hms123456
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - hms-network

  frontend:
    build: ./Frontend_HMS/HMS
    image: angular-frontend
    container_name: angular-app
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - hms-network

  redis:
    image: redis:7-alpine
    container_name: hms-redis
    ports:
      - '6379:6379'
    networks:
      - hms-network

networks:
  hms-network:
    driver: bridge